# Generated by Django 3.2.7 on 2021-11-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='nic',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='NIC'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
