# Generated by Django 3.2.7 on 2021-11-21 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_license_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='license',
            options={'ordering': ('license',)},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ('location',)},
        ),
        migrations.AlterUniqueTogether(
            name='license',
            unique_together={('location', 'license')},
        ),
    ]
