# Generated by Django 3.2.7 on 2021-11-21 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_client_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='licenses',
            field=models.ManyToManyField(blank=True, to='payments.License'),
        ),
    ]
