# Generated by Django 3.2.7 on 2021-11-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_alter_client_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='annual_fee',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
        ),
    ]
