# Generated by Django 3.2.7 on 2021-11-21 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='balance',
        ),
    ]
