# Generated by Django 3.2.7 on 2021-11-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_remove_payment_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
            ],
        ),
    ]
