# Generated by Django 3.2.7 on 2021-11-21 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_rename_paymentyear_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='payments.year'),
        ),
    ]
