# Generated by Django 3.2.7 on 2021-11-21 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0016_auto_20211121_1622'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LicenseIssue',
            new_name='LicenseItem',
        ),
        migrations.RenameModel(
            old_name='Payment',
            new_name='LicensePayment',
        ),
    ]
