# Generated by Django 3.2.7 on 2021-11-21 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0017_auto_20211121_1628'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('client_name',)},
        ),
        migrations.RenameField(
            model_name='client',
            old_name='name',
            new_name='client_name',
        ),
        migrations.AddField(
            model_name='client',
            name='slug',
            field=models.SlugField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
