# Generated by Django 3.2.7 on 2021-11-22 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0019_alter_client_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
