# Generated by Django 3.2.7 on 2021-11-22 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0020_license_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenseitem',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.location'),
        ),
        migrations.AlterUniqueTogether(
            name='license',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='license',
            name='location',
        ),
    ]
