# Generated by Django 3.2.7 on 2021-11-22 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0021_auto_20211122_0423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licensepayment',
            name='client',
        ),
        migrations.RemoveField(
            model_name='licensepayment',
            name='year',
        ),
        migrations.AddField(
            model_name='licensepayment',
            name='license_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.licenseitem'),
        ),
        migrations.AlterField(
            model_name='license',
            name='annual_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
