# Generated by Django 3.2.7 on 2021-11-22 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0022_auto_20211122_0429'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LicenseItem',
            new_name='IssuedLicense',
        ),
    ]
