# Generated by Django 3.2.7 on 2021-11-22 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0023_rename_licenseitem_issuedlicense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedlicense',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_license_years', to='payments.year'),
        ),
    ]
