# Generated by Django 3.2.7 on 2021-11-22 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0024_alter_issuedlicense_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedlicense',
            name='license',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_licenses', to='payments.license'),
        ),
        migrations.AlterField(
            model_name='issuedlicense',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.year'),
        ),
    ]
