# Generated by Django 3.2.7 on 2021-11-22 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0027_alter_issuedlicense_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='licensepayment',
            old_name='license_item',
            new_name='issued_license',
        ),
    ]
