# Generated by Django 3.2.7 on 2021-11-22 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0029_auto_20211122_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year',
            name='year',
            field=models.IntegerField(unique=True),
        ),
    ]
