# Generated by Django 3.2.7 on 2021-11-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0030_alter_year_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='licensepayment',
            options={'ordering': ('issued_license__year',)},
        ),
        migrations.AlterModelOptions(
            name='year',
            options={},
        ),
        migrations.RemoveField(
            model_name='year',
            name='slug',
        ),
        migrations.AddField(
            model_name='licensepayment',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
